# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: 
      - 'practice_5-domchenko'
  pull_request:
    branches:
      - 'practice_5-domchenko'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        cd ./practice_5-domchenko/
        sudo apt install make python3-venv
        make deps
    - name: Lint with flake8
      run: |
        cd ./practice_5-domchenko/
        make lint
    - name: Test with pytest
      run: |
        cd ./practice_5-domchenko/
        make test
